const id = "en/index.md";
						const collection = "homepage";
						const slug = "en";
						const body = "";
						const data = {banner:{title:"Focus on Patient Care, Not Paperwork",content:"Automate your billing process with our billing co-pilot.",image:"/images/main_img.webp",button:{label:"Contact Us",link:"/contact",enable:true}},feature:{title:"Our solutions",features:[{name:"AI co-pilot",icon:"/images/code.svg",content:"We use AI to automatically identify accurate medical coding from doctors note"},{name:"Compliant",icon:"/images/oop.svg",content:"We are compliant with the Swiss medical coding and insurance, less time to worry about insurance claims"},{name:"Customer Service",icon:"/images/user-clock.svg",content:"We are available 24*7"},{name:"Value for money",icon:"/images/love.svg",content:"We identify missed revenue opportunities that already pays for the services"},{name:"Private swiss cloud",icon:"/images/cloud.svg",content:"Privacy by design. We understand privacy. Your data never leaves Switzerland"},{name:"Bill understanding",icon:"/images/phone.svg",content:"Scan or upload your bill to understand what each item is about."}]},app:{title:"Understand your bills",apple:"/images/apple.webp",apple_link:"#",google:"/images/google.webp",google_link:"#"},services:[{title:"The most advanced billing automation",content:"We offer the most advanced billing automation, leveraging cutting-edge technology for streamlined invoicing and payment processing, offering unparalleled efficiency and security. Intuitive interface and customizable features empower organizations to optimize their financial operations and stay ahead in the competitive business landscape with ease.",images:["/images/img_9.webp"],button:{enable:true,label:"Check it out",link:"/contact"}},{title:"Accurate medical coding",content:"We use AI to automatically identify accurate medical coding. Our cutting-edge technology optimizes billing by ensuring targeted accuracy.",images:["/images/img_17.webp"],button:{enable:true,label:"Check it out",link:"/contact"}},{title:"Increase revenue and claim rate through automation",content:"We identify the missed revenue opportunities and missing items in the bills. Making bills more accurate and compliant with the insurance.",images:["/images/img_13.webp","/images/img_4.webp"],button:{enable:true,label:"Check it out",link:"/contact"}},{title:"We are an experienced team",content:"We have decades of experience developing world-class systems. We understand privacy, compliance and customers’s needs. We are committed to providing the best possible service to our customers.",images:["/images/img_12.webp"],button:{enable:true,label:"Check it out",link:"/contact"}}],workflow:{title:"Find the solution to your needs with us.",image:"/images/main_img.webp",description:""},call_to_action:{title:"Ready to get started?",content:"Click below and contact us.",image:"/images/cta.png",button:{enable:true,label:"Contact Us",link:"/contact"}}};
						const _internal = {
							type: 'content',
							filePath: "/home/pankaj/Projects/fisca/landing/website/src/content/homepage/en/index.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
